[project]
name = "assessment-crew"
version = "0.1.0"
description = "CrewAI-based Java codebase modernization assessment tool"
readme = "README.md"
requires-python = ">=3.10,<4.0"

dependencies = [
  "crewai>=0.1.0",
  "openai>=0.27.0",
  "anthropic>=0.3.0",
  "python-dotenv>=0.21.0",
  "PyYAML>=6.0",
  "javalang>=0.13.0",
]

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
