# src/crews/code_gen/config/tasks.yaml

# src/crews/code_gen/config/tasks.yaml

create_modernization_step_brief:
  description: >
    For the current modernization plan step (identified as '{current_plan_step_identifier}', 
    previous feedback if any: '{retry_feedback_notes}'), 
    thoroughly analyze all relevant information sources:
    1. The **generated legacy application documentation** (accessible via CodeSearchTool with target '1-documentation/docs').
    2. The **general knowledge base documents** (accessible via CodeSearchTool with target 'kb-docs').
    3. The entire **code example knowledge base** (accessible via CodeSearchTool with target 'kb-code').
    
    Synthesize these findings into a comprehensive "Modernization Step Brief".
    This brief must clearly state the step's objectives. 
    It must incorporate detailed analysis from the **generated legacy application documentation** relevant to the current step.
    It must highlight best practices from the **general knowledge base documents**.
    And critically, it must provide specific code examples, warnings, workarounds, and direct guidance from the **code example knowledge base** ('kb-code'). 
    Emphasize 'kb-code' as the primary source of truth for concrete implementation patterns.
  expected_output: >
    A detailed "Modernization Step Brief" document (string format) containing:
    1. Current plan step objectives.
    2. Relevant analysis summary from the generated legacy application documentation.
    3. Applicable patterns from the general knowledge base documents.
    4. Crucial code examples, solutions, and warnings from the code example knowledge base ('kb-code').
    5. Clear guidance on how 'kb-code' informs this specific step.
  agent: software_architect

implement_code_changes:
  description: >
    Based on the provided "Modernization Step Brief" ({create_modernization_step_brief_task}), implement the required code transformations.
    Write new Java 21 / Spring Boot code or modify existing code in the designated working directory ({working_code_path_for_this_step}).
    Ensure all code generation heavily references and adheres to the guidance, examples, and solutions
    provided by the Software Architect as highlighted in the brief.
    Compile the modernized Java 21 / Spring Boot code located in the working directory 
    (path from 'implement_code_changes' task output: {implement_code_changes_task.changed_files_path}). 
    If the "Modernization Step Brief" or plan step specifies, also compile the legacy codebase 
    (path: {legacy_code_path_for_this_step}) using the LegacyCompilerTool for baseline or comparison.
  expected_output: >
    Code that compiles, if it not compile search for a solution based on the documents provided by the Software Architect.
    If you can't find a solution there, serach the web.
  agent: principal_software_engineer
  human_input: true
