# src/crews/code_gen/config/tasks.yaml
implement_code_changes:
  description: >
    Working Directory for your changes:  'code'.
    Based *solely* on the "Modernization Step Brief" provided above:
    1. Implement the required code transformations in the specified working directory. 
      This may involve writing new Java 21 / Spring Boot code, modifying existing Java code, 
      and updating pom.xml files using your file system tools. 
      Ensure all code generation heavily references the guidance from the brief.
    2. After making changes, you MUST attempt to compile the entire multi-module project located in the 
       working directory requesting the build_agent to build it using its tool. 
    3. If the build_agent reports any compilation errors: 
       - Analyze the errors. 
       - Consult the brief 
       - Ask the software_architect to get some more insight about the documentation and he can find something 
         that may help to solve the issue.
       - As last resort search the web using SerperDevTool and WebsiteSearchTool
         for solutions. Attempt to fix the errors and re-compile. 
         You may attempt this fix-and-compile cycle up to 10 times.
    It is **MANDATORY** that when you try to open a file for read or write a file you use the full path as provided by the DirectoryReadTool
    It is **MANDATORY** that you make a list of the files you read and you compare with the result of DirectoryReadTool
    to make sure you read all the docs
    After your attempts (successful or not), present the following to the human for review:
    Compilation Status, Compilation Logs, Summary of Changes Made, and the path to the changed files.
    Then, ask the human for their decision: 'approve' or 'reject'.
    If you get compile errors from the build tool, try too open all the files reported in the error and
    pass to the LLM and try to understand where the problem is and find a fix.
    You shall also use the
    You now have the MavenBuildTool you build if it doesn't work you try to fix by asking to the software_architect
    for infos, if he cannot provide anything meaningful you search the web
    **Very Important** to create a new directory you need to use the FileWriterTool and create a dummy file in it
    this is the only way you can create a folder
  expected_output: >
    New or changed code added to the repository, hopefully with a successful build.
  agent: principal_software_engineer

build_solution:
  description: >
    Working Directory: 'code'.  
    Instruct the build_agent to invoke the MavenBuildTool on the entire multi-module project  
    and capture all output.  
    Report back the overall build status (success or failure) along with the full Maven logs.
  expected_output: >
    A report containing:
    1. Build Status (e.g., “SUCCESS” or “FAILURE”)
    2. The complete Maven console output/logs.
  agent: build_agent

evaluate_solution:
  description: >
    After the principal_software_engineer’s changes (regardless of build success), collect:
      1. Compilation Status
      2. Full Compilation Logs
      3. Summary of Changes Made
      4. Paths to all modified/added files  
    Present this package to the human for review and explicitly prompt for a decision of “approve” or “reject.”
  expected_output: >
    A human‐facing report containing the four items above and a clear “approve” or “reject” response.
  agent: team_lead
  human_input: true


